[workspace]
resolver = "2"
members = [
    "allwinner-hal",
    "allwinner-rt",
    "allwinner-rt/macros",
    "examples/nezha-d1",
    "examples/sdmmc",
    "rfel",
]

[workspace.package]
edition = "2024"
license = "MulanPSL-2.0 OR MIT"
repository = "https://github.com/rustsbi/allwinner-hal"
