name: CI

on: [push,pull_request]

env:
  CARGO_TERM_COLOR: always
  # By default, RUSTFLAGS with “-D warnings” turns “asm_const” warnings into errors.
  RUSTFLAGS:

jobs:
  fmt:
    name: Rustfmt all packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
  
  build-allwinner-rt:
    name: Build allwinner-rt
    needs: fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: [riscv64imac-unknown-none-elf]
        TOOLCHAIN: [nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ MATRIX.TARGET }}
          toolchain: ${{ MATRIX.TOOLCHAIN }}
      - name: Run build
        run: cargo build -p allwinner-rt --target ${{ MATRIX.TARGET }}
  
  test-allwinner-hal:
    name: Test allwinner-hal
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Run tests
        run: cargo test